version: "3"

services:

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /etc/sabnzbd:/config
      - /media/complete:/downloads
      - /media/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - /etc/sonarr:/config
      - /media/complete/tv:/tv
      - /media/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - /etc/plex:/config
      - /media/complete/tv:/tv
      - /media/complete/movies:/movies
    restart: unless-stopped
volumes:
  mymedia: